apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-prod-deployment
  namespace: default
  labels:
    app: medicure-prod-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure-prod-app
  template:
    metadata:
      labels:
        app: medicure-prod-app
    spec:
      containers:
      - name: medicure-prod-app
        image: krishna21290/medicure-app:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: medicure-prod-service
  namespace: default
spec:
  selector:
    app: medicure-prod-app
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8082
    protocol: TCP
    nodePort: 31001
